### ISSUE TITLE
/var/lib/gems/2.7.0/gems/mosbot-2.0.1/lib/mosbot.rb:49: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

### ISSUE THREAD

**Issue by ket000** [psadmin-io/mosbot-cli#18]
Can we update the code to avoid this warning. 

mosbot doc 2936124.1
/var/lib/gems/2.7.0/gems/mosbot-2.0.1/lib/mosbot.rb:49: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
E-IB: Where are the Host, Port, and Default Local Node Retrieved from in a PeopleSoft Provider Service Definition's REST Base URL, and is it Possible to Change them? 
https://support.oracle.com/epmos/faces/DocumentDisplay?id=2936124.1

**Comment by iversond** [comment]
Hi Ketan - this has been changed.

**Comment by iversond** [comment]
`gem install mosbot` will now pull down version 2.0.2.
